### ISSUE TITLE
新工程嵌入的时候，报Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference

### ISSUE THREAD

**Issue by JackyKeke** [MichaelJokAr/MultiLanguages#20]
Process: com.example.multilanguage2, PID: 22233
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.multilanguage2/com.example.multilanguage2.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
        at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:159)
        at android.app.FragmentManagerImpl.getTargetSdk(FragmentManager.java:2978)
        at android.app.FragmentManagerImpl.attachController(FragmentManager.java:2967)
        at android.app.FragmentController.attachHost(FragmentController.java:86)
        at android.app.Activity.attach(Activity.java:7366)

**Comment by JackyKeke** [comment]
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.example.multilanguage2"
        minSdkVersion 16
        targetSdkVersion 27}
}
