### ISSUE TITLE
Service报错崩溃

### ISSUE THREAD

**Issue by gowcage** [MichaelJokAr/MultiLanguages#7]
继承 Service
错误信息：
2019-10-10 15:28:18.438 31956-31956/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: gqz.pager, PID: 31956
    java.lang.NoSuchMethodError: No super method attachBaseContext(Landroid/content/Context;)V in class Landroid/content/ContextWrapper; or its super classes (declaration of 'android.content.ContextWrapper' appears in /system/framework/framework.jar)
        at gqz.pager.service.MyService.attachBaseContext(Unknown Source:4)
        at android.app.Service.attach(Service.java:761)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3337)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by gowcage** [comment]
我是在Application的onCreate中调用的启动服务，在你的sdk方法MultiLanguage.init()和MultiLanguage.setApplicationLanguage(this);之后调用

**Comment by iostyle** [comment]
同样的问题 各个service一直报错 请问解决了吗

**Comment by MichaelJokAr** [comment]
请问是用的最新版本的么：
`classpath 'com.github.jokar:multi-languages.plugin:0.0.3'

implementation 'com.github.jokar:multi-languages:0.0.4'
`

**Comment by MichaelJokAr** [comment]
已修复，使用 v0.0.5版本，谢谢反馈
